const PRIMARY_COLOR = '#7610EB';
const SECONDARY_COLOR = '#FFFFFF';
const BACKGROUND_COLOR = '#F1F2F4';
const TEXT_REGULAR = 'AvenirNextCyr-Regular';
const TEXT_DEMI = 'AvenirNextCyr-Demi';
const TEXT_BOLD = 'AvenirNextCyr-Bold';
const HEADER_TEXT_SIZE = 17;

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACKGROUND_COLOR,
  TEXT_REGULAR,
  TEXT_DEMI,
  TEXT_BOLD,
  HEADER_TEXT_SIZE,
};
