import { StyleSheet, Platform } from 'react-native';
import { TEXT_REGULAR } from './fonts';
import { PRIMARY_COLOR } from './constants';
export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
  },
  body: {
    flex: 1,
    marginTop: 114,
  },
  footer: {
    marginBottom: Platform.OS === 'ios' ? 35 : 5,
  },
  titleText: {
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 33,
    letterSpacing: 0.0041,
    fontFamily: TEXT_REGULAR,
    marginBottom: 24,
  },
  bodyText: {
    fontSize: 17,
    lineHeight: 23,
    letterSpacing: 0.0041,
    color: '#6B7583',
    fontFamily: TEXT_REGULAR,
  },
  labelText: {
    fontSize: 14,
    color: '#ACB5BE',
    marginBottom: 10,
    fontWeight: '400',
    lineHeight: 19,
    letterSpacing: 0.0012,
  },
  textInput: {
    fontFamily: TEXT_REGULAR,
    fontSize: 25,
    borderBottomColor: '#F1F2F4',
    borderBottomWidth: 2,
    paddingVertical: 4,
  },
  mainButton: {
    marginBottom: 5,
    backgroundColor: PRIMARY_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    height: 55,
    borderRadius: 27.5,
    marginTop: 10,
  },
  mainButtonText: {
    color: 'white',
    fontSize: 17,
    fontWeight: '500',
    fontFamily: TEXT_REGULAR,
  },
  subButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 55,
    borderRadius: 30,
  },
  subButtonText: {
    color: 'white',
    fontSize: 17,
    fontWeight: '500',
    fontFamily: TEXT_REGULAR,
  },
  roundButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 100,
    width: 64,
    height: 64,
  },
  linkedBankContainer: {
    justifyContent: 'space-between',
    height: 62,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  linkedBankText: {
    flex: 1,
    fontFamily: TEXT_REGULAR,
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 23,
    letterSpacing: -0.041,
  },
  subscriptionsFoundText: {
    flex: 1,
    fontFamily: TEXT_REGULAR,
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 23,
    letterSpacing: -0.041,
  },
});
