require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sureplus_moscato' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'react-native-sms', :path => '../node_modules/react-native-sms'

  target 'sureplus_moscatoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
    post_install do |installer|
      flipper_post_install(installer)
  end
end

target 'sureplus_moscato-tvOS' do
  # Pods for sureplus_moscato-tvOS

  target 'sureplus_moscato-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
