before_all do
    ensure_git_branch
    ensure_git_status_clean
    git_pull
end

platform :ios do
    private_lane :update_version do
        version = get_app_store_version_number(bundle_id: 'sureplus.io')
        plist_version = get_version_number_from_plist(xcodeproj: './ios/sureplus_moscato.xcodeproj')
        if Gem::Version.new(plist_version.to_f) == Gem::Version.new(app_store_version.to_f)
            UI.message "bumping minor"
            increment_version_number_in_plist(xcodeproj: './ios/sureplus_moscato.xcodeproj', bump_type: 'minor')
        else 
            UI.message "bumping patch"
            increment_version_number_in_plist(xcodeproj: './ios/sureplus_moscato.xcodeproj', bump_type: 'patch')
        end
    end

    private_lane :staging_build do
        increment_build_number_in_plist(xcodeproj: './ios/sureplus_moscato.xcodeproj', target: 'sureplus_moscato')
        gym(scheme: 'sureplus_moscato', workspace: './ios/sureplus_moscato.xcworkspace')
    end

    lane :beta do
        staging_build
        upload_to_testflight(username: 'jaehwan@sureplus.io', app_identifier: 'sureplus_moscato')
        commit_version_bump(message: 'bump build')
        push_to_git_remote
    end
end 

platform :android do
    desc "Android build and release to beta"
    lane :beta do
        increment_version_code(app_project_dir: './android/app')
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(track: 'beta', aab: './android/app/build/outputs/bundle/release/app-release.aab')
    end
end