name: Build Android and iOS
on:
  push:
    branches:
      - master
      - amplify
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install Pods
        run: |
          cd ios && pod install
      - name: Run iOS build
        run: |
          react-native run-ios
