name: Build iOS
on:
  push:
    branches:
      - master
      - amplify
jobs:
  install-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace sureplus_moscato.xcworkspace \
          -configuration Debug \
          -scheme sureplus_moscato \
          -destination id=DB4C617D-5251-4BE7-BA79-0ADADB0D903D"
