name: Build iOS
on:
  push:
    branches:
      - master
      - amplify
      - maro_branch
  pull_request:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild -allowProvisioningUpdates \
          -workspace ios/sureplus_moscato.xcworkspace \
          -configuration Debug \
          -scheme sureplus_moscato"
