name: Build iOS
on:
  push:
    branches:
      - master
      - amplify
jobs:
  install-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/sureplus_moscato.xcworkspace \
          -scheme sureplus_moscato \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/sureplus_moscato \
          CODE_SIGNING_ALLOWED=NO"
